# Generated by Django 5.0.3 on 2024-03-29 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 15, 58, 15, 512176)),
        ),
    ]
