# Generated by Django 5.0.3 on 2024-03-30 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 18, 48, 40, 598890)),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['-timestamp'], name='comments_co_timesta_2ae60d_idx'),
        ),
    ]
